name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Apply Version to JSON file
      uses: rfennell/JSONFileVersioner@v1
      with:
      path: 'testdata'
      field: 'version'
      VersionNumber: '1.2.3'
      filenamepattern: '.json' 
      recursion: 'true'
